export const constants = {
  siteName: "bouwe.io",
  siteUrl: "https://bouwe.io",
  siteDescription: "bouwe.io, a blog by Bouwe Westerdijk",
  language: "en",
  siteImage: "https://bouwe.io/bouwe-react-amsterdam.png",
  faviconDefault: "https://bouwe.io/favicon.ico",
  copyright: `All rights reserved 2019 - ${new Date().getFullYear()}, Bouwe Westerdijk`,
  authorName: "Bouwe Westerdijk",
  authorEmail: "bouwe@bouwe.nl",
  authorLink: "https://bouwe.io",
  gitHubRepoUrl: "https://github.com/bouwe77/bouwe.io",
  gitHubEditUrl: "https://github.com/bouwe77/bouwe.io/edit/master/",
  categoryPageTitle: "Blog posts about",
  logo: "bouwe!",
};
