name: Publish Markdown and static assets to 'docs' folder

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out the repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Publish Markdown to HTML
        run: npm run publish
